{% set name = "mdsynthesis" %}
{% set version = "0.6.1" %}
{% set sha256 = "95f48f9e2fd5dbd031b08de87ab682921895b336a855807ef95cdd876315cdc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  skip: True  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - datreant <=1.0.0
    - datreant.core
    - datreant.data
    - mdanalysis >=0.17.0

test:
  imports:
    - mdsynthesis

about:
  home: https://mdsynthesis.readthedocs.io/en/master/
  license: GPL-2.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'a persistence engine for molecular dynamics data'
  description: |
    As computing power increases, it is now possible to produce hundreds of molecular 
    dynamics simulation trajectories that vary widely in length, system size, composition, 
    starting conditions, and other parameters. Managing this complexity in ways that allow 
    use of the data to answer scientific questions has itself become a bottleneck. 
    MDSynthesis is an answer to this problem.
  dev_url: https://github.com/datreant/MDSynthesis

extra:
  recipe-maintainers:
    - kain88-de
    - orbeckst
