travis:
  secure:
    BINSTAR_TOKEN: Ym8WrPK6t0kJDzFqeOd55MB0yKT24lTRQBfYqWdDPafqbowvN+aMDzf9D34bXlZw5lur0ic4vZgFRhDcZfnYgef+KdYsUs52/9eSxVsZ1EhmjnssNgvdvNV9jx4xy+8/mXqZo6d9FWlNBD6oITRSGlqgVNOVUYO3fNiwxDOZj8TUG7Hvm4jB0vWPaV0/Q3Eu9cGO3J/0Z068LyLJHFGrvDBWblPPiS2AfKJ15WNyN501fyM8QH1C3haBP+T39xRU+iJNPr7H4uMv1bDOYXkfDVY9/3nWWQ0Ci7eU74J+WDsWOis0C1DNaKTss21NQAfXJ/M4gm0rifZkJ/FHw4zXA3qB3CyQiGNNKKpDeM7jNSyCp7nG8BzVk4gIJ5KK83Qspn2mnUOZH0Fo3n7u6glA2G5ujvJE8Ri2+ulIJTr3Jh9L3KXzSSXcSnNHxaHrNJnJQoNRuUUwdmDjrqj3tI74gmDAi7Gx7zepHNRaZFz/0Hg/S78Fb4WRm+HW1WpAUVc6yJrCY27VCDFf9DUrPEUcz8mYeLwk0aHydSTwNRVExeCyHdaOgWH8aAMjP6WDmLhZ9/BF872D9BFg12ZUuB2Yb5waXuw+lHQpt4jJ30z6nVTWiszkJp3arTNhLBSF5qnFAa4pY+HmOGG+oY9caaASbLTxVmA3QMvD897LuR3YX6o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
