travis:
  secure:
    BINSTAR_TOKEN: S0I1NBhFIauTHWaLEMC53tbs6oVsS75x7UI066PJsaQpAIQtGcZC2pvtkwoQ0AVT3Eev6gM2qyt+46ry0iLTf2rDllV+a+TL5A34G08E1l8W2Cy+evIEg7v7rG1a7+4QFCbaQb7ExHz+2s24r6Crf3ZBj5MtAhTO5Sok3ERC0jLgPrF+YwGKllp+sRwaDxQ5qVS97JgkI2Wm+fyQv2sujMyC7h7beo+4S9PYzhnWM2FWPVBLNLyDEBawCa3UbxoSmETnfS/4h2PQZY1zKX96ANtnt2/0Cj1MA7zYaeVW4XQnfnRvGfvvAIqB9gdZ3q5rkshpc8iHWgprWRyZZ/2uik9dJXqINq+OvrR37c6QlJ46Ag3KCmR1+0f8BHIN13kHkHvIb/3atoAHyy7ZFq1pa/8y7dlkPZm5iHn0K88q7MvwVdTnGKcXMxe4rRbAvTusD2qq0sb7iEQFqneSJ2dMb0Dd/57wzR0zMUj4VhHnmwx4OOsXfLgCXCsl3yPfEiSppx5XHDRUwNGjsLpbaHODXLVbaS9kAeD/fdxDPQrCW0CSHzkM8LeXTswpWi8Z0BepOxqVKaFofv9fD/4lzhSYSIsvjxF90nqcNvGb4NtR3R0k96OYtjjWoM+X+WG9UCUechynmGC7U4oKmA3gQb0wk/6TpRzgUmXv3kXMJZjZlEg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
